/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package technosciencemanagementsystem;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author MICHAEL
 */
public class RegistrationSystemUsers extends javax.swing.JFrame {
     private JFrame frame;
      Connection con =null;
      PreparedStatement pst = null;
      ResultSet rs = null;
    public RegistrationSystemUsers() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nam = new javax.swing.JTextField();
        phon = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        position = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        usern = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        answ = new javax.swing.JTextField();
        ext = new javax.swing.JButton();
        bck = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        Reg = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        passw = new javax.swing.JPasswordField();
        pass = new javax.swing.JPasswordField();
        quest = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), " SYSTEM USERS REGISTRATION FORM", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Elephant", 1, 24), new java.awt.Color(51, 51, 255))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Engravers MT", 1, 18)); // NOI18N
        jLabel1.setText("Names:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 182, 40));

        jLabel3.setFont(new java.awt.Font("Engravers MT", 1, 18)); // NOI18N
        jLabel3.setText("Phonenumber:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 200, 37));

        nam.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(nam, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 270, -1));

        phon.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(phon, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 270, -1));

        jLabel2.setFont(new java.awt.Font("Engravers MT", 1, 18)); // NOI18N
        jLabel2.setText("Role:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        position.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        position.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose Role", "Admin", "Secretary", "Treasurer", "Project Manager" }));
        jPanel1.add(position, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 270, -1));

        jLabel5.setFont(new java.awt.Font("Engravers MT", 1, 18)); // NOI18N
        jLabel5.setText("username:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 174, 37));

        usern.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(usern, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 270, -1));

        jLabel7.setFont(new java.awt.Font("Engravers MT", 1, 18)); // NOI18N
        jLabel7.setText("password:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, -1, -1));

        jLabel8.setFont(new java.awt.Font("Engravers MT", 1, 18)); // NOI18N
        jLabel8.setText("Security Question:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, -1));

        jLabel9.setFont(new java.awt.Font("Engravers MT", 1, 18)); // NOI18N
        jLabel9.setText("Security Answer");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, -1, -1));

        answ.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        answ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answActionPerformed(evt);
            }
        });
        jPanel1.add(answ, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 530, 270, -1));

        ext.setBackground(new java.awt.Color(204, 255, 204));
        ext.setFont(new java.awt.Font("Engravers MT", 1, 18)); // NOI18N
        ext.setForeground(new java.awt.Color(153, 153, 0));
        ext.setText("Exit");
        ext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extActionPerformed(evt);
            }
        });
        jPanel1.add(ext, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 590, -1, -1));

        bck.setBackground(new java.awt.Color(255, 255, 204));
        bck.setFont(new java.awt.Font("Engravers MT", 1, 18)); // NOI18N
        bck.setForeground(new java.awt.Color(153, 0, 255));
        bck.setText("Back");
        bck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bckActionPerformed(evt);
            }
        });
        jPanel1.add(bck, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 590, -1, -1));

        reset.setBackground(new java.awt.Color(255, 204, 204));
        reset.setFont(new java.awt.Font("Engravers MT", 1, 18)); // NOI18N
        reset.setForeground(new java.awt.Color(51, 51, 255));
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel1.add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 590, -1, -1));

        Reg.setBackground(new java.awt.Color(204, 204, 255));
        Reg.setFont(new java.awt.Font("Engravers MT", 1, 18)); // NOI18N
        Reg.setForeground(new java.awt.Color(0, 255, 204));
        Reg.setText("Register");
        Reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegActionPerformed(evt);
            }
        });
        jPanel1.add(Reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 590, -1, -1));

        jLabel6.setFont(new java.awt.Font("Engravers MT", 1, 18)); // NOI18N
        jLabel6.setText("Confirm Password:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, -1, -1));

        passw.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(passw, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, 270, 28));

        pass.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 270, -1));

        quest.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        quest.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Your Security Question", "What is your Favorite Pet?", "What is your Favorite Dream Country?", "What is your Hobby?" }));
        jPanel1.add(quest, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 470, 270, -1));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 0));
        jLabel4.setText("Fill in your details in form below to be registered in the system and to use the system");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 580, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void extActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extActionPerformed
         //You must declare the Jframe on the top
        frame = new JFrame();
         if (JOptionPane.showConfirmDialog(frame, "Cofirm if you want to exit", "System Users Registration Form",
             JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION){
             System.exit(0);
         }
    }//GEN-LAST:event_extActionPerformed

    private void bckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bckActionPerformed
           LoginForm fml = new LoginForm();
           fml.setVisible(true);
           this.dispose();       
    }//GEN-LAST:event_bckActionPerformed

    private void RegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegActionPerformed
        try{
      
        String sql = " INSERT INTO account (names, username, phonenumber, role, Password, confirmpassword, security_question, answer )  VALUES (?,?,?,?,?,?,?,?)";
        con = DriverManager.getConnection("jdbc:mysql://localhost/tms","root","");
        pst = con.prepareStatement(sql);
        pst.setString(1, nam.getText());
        pst.setString(2, usern.getText());
        pst.setString(3, phon.getText());
        pst.setString(4, position.getSelectedItem().toString());
        pst.setString(5, pass.getText());
        pst.setString(6, passw.getText());
        pst.setString(7, quest.getSelectedItem().toString());
        pst.setString(8, answ.getText());
        
           
         if(nam.getText().equals("") || phon.getText().equals("") || usern.getText().equals("") || answ.getText().equals("") 
                 || pass.getText().equals("") || passw.getText().equals("") || position.getSelectedIndex()==0 || quest.getSelectedIndex()==0 ){
             JOptionPane.showMessageDialog(null,"Some fields not filled in..!!\n Please Fill them to continue.","Warning",JOptionPane.WARNING_MESSAGE);
          }
            
        if( !pass.getText().equals (passw.getText())){
            JOptionPane.showMessageDialog(null,"Passwords are not the same!!!");
        }
        else {
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Registration of Techno science Leaders is Successful");
               phon.setText(" ");
               nam.setText(" ");
               phon.setText(" ");
               position.setSelectedIndex(0);
               quest.setSelectedIndex(0);
               pass.setText("");
               passw.setText("");
               answ.setText(""); 
               usern.setText("");
               this.dispose();
               LoginForm lgm = new LoginForm();
               lgm.setVisible(true);
        }
        } 
        catch(HeadlessException | SQLException ex){
        JOptionPane.showMessageDialog(null,ex);
        }
    }//GEN-LAST:event_RegActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
           phon.setText(" ");
           nam.setText(" ");
           phon.setText(" ");
           pass.setText("");
           passw.setText("");
           position.setSelectedIndex(0);
           quest.setSelectedIndex(0);
           answ.setText(""); 
           usern.setText("");
    }//GEN-LAST:event_resetActionPerformed

    private void answActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationSystemUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationSystemUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationSystemUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationSystemUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationSystemUsers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Reg;
    private javax.swing.JTextField answ;
    private javax.swing.JButton bck;
    private javax.swing.JButton ext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nam;
    private javax.swing.JPasswordField pass;
    private javax.swing.JPasswordField passw;
    private javax.swing.JTextField phon;
    private javax.swing.JComboBox position;
    private javax.swing.JComboBox<String> quest;
    private javax.swing.JButton reset;
    private javax.swing.JTextField usern;
    // End of variables declaration//GEN-END:variables
}
